config/routes.rb
Rails.application.routes.draw do
  resources :f_dzakirs
  resources :f_dpetras
  resources :f_droberts
  resources :f_develyns
  resources :f_dcarries
  resources :f_dowais
  resources :f_djosephs
  resources :f_dalexis
  resources :f_dhalles
  resources :f_dmikaels
  resources :medical_students
  
  devise_for :users
  # Professor told me to move "devise_for :users" after the "resources :users, only: [:show, :edit, :update, :index]". But if I do, the "Too many redirects" error is produced. 
  # Found this on Github: https://github.com/heartcombo/devise/issues/367
  # "RegistrationsController does not allow you to access the new action when you
  # are signed in. If you are signed in and try to access it, it redirects you
  # back to the root_path. Which is going to redirect you again and again.
  
  # My advice is to create another controller which shows you the sign up form,
  # but sends you to the proper registrations controller."
  resources :users, only: [:show, :edit, :update, :index]


  root "users#show" # Changed "users#index" to "users#show" and it sent me to the profile page!
  resources :sign_ins
  resources :join_nows
  
  resources :research_submissions
  resources :blogs do
    resources :comments
  end
  resources :abouts
  resources :specifics
  resources :specialties
  resources :articles
  resources :homes
  

  get 'home/index'
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    validates_presence_of :title
    validates_presence_of :body
    validates_presence_of :author_name
    validates_presence_of :post_type
 #   validates_presence_of :image_url
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/f_dalexi.rb
class FDalexi < ApplicationRecord
end

app/models/f_dcarrie.rb
class FDcarrie < ApplicationRecord
end

app/models/f_develyn.rb
class FDevelyn < ApplicationRecord
end

app/models/f_dhalle.rb
class FDhalle < ApplicationRecord
end

app/models/f_djoseph.rb
class FDjoseph < ApplicationRecord
end

app/models/f_dmikael.rb
class FDmikael < ApplicationRecord
end

app/models/f_dowai.rb
class FDowai < ApplicationRecord
end

app/models/f_dpetra.rb
class FDpetra < ApplicationRecord
end

app/models/f_drobert.rb
class FDrobert < ApplicationRecord
end

app/models/f_dzakir.rb
class FDzakir < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/join_now.rb
class JoinNow < ApplicationRecord
end

app/models/sign_in.rb
class SignIn < ApplicationRecord
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/models/specific.rb
class Specific < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/f_develyns_controller.rb
class FDevelynsController < ApplicationController
  before_action :set_f_develyn, only: [:show, :edit, :update, :destroy]

  # GET /f_develyns
  # GET /f_develyns.json
  def index
    @f_develyns = FDevelyn.all
  end

  # GET /f_develyns/1
  # GET /f_develyns/1.json
  def show
  end

  # GET /f_develyns/new
  def new
    @f_develyn = FDevelyn.new
  end

  # GET /f_develyns/1/edit
  def edit
  end

  # POST /f_develyns
  # POST /f_develyns.json
  def create
    @f_develyn = FDevelyn.new(f_develyn_params)

    respond_to do |format|
      if @f_develyn.save
        format.html { redirect_to @f_develyn, notice: 'F develyn was successfully created.' }
        format.json { render :show, status: :created, location: @f_develyn }
      else
        format.html { render :new }
        format.json { render json: @f_develyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /f_develyns/1
  # PATCH/PUT /f_develyns/1.json
  def update
    respond_to do |format|
      if @f_develyn.update(f_develyn_params)
        format.html { redirect_to @f_develyn, notice: 'F develyn was successfully updated.' }
        format.json { render :show, status: :ok, location: @f_develyn }
      else
        format.html { render :edit }
        format.json { render json: @f_develyn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /f_develyns/1
  # DELETE /f_develyns/1.json
  def destroy
    @f_develyn.destroy
    respond_to do |format|
      format.html { redirect_to f_develyns_url, notice: 'F develyn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_f_develyn
      @f_develyn = FDevelyn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def f_develyn_params
      params.fetch(:f_develyn, {})
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/f_develyns_helper.rb
module FDevelynsHelper
end

app/views/f_develyns/_form.html.erb
<%= simple_form_for(@f_develyn) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/f_develyns/edit.html.erb
<h1>Editing F Develyn</h1>

<%= render 'form', f_develyn: @f_develyn %>

<%= link_to 'Show', @f_develyn %> |
<%= link_to 'Back', f_develyns_path %>

app/views/f_develyns/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <nav id="navbar-article" class="navbar sticky-top navbar-light bg-light flex-column">
        <a class="navbar-brand" href="#">
          <form class="form-inline">
            <!--<div class="input-group">-->
            <!--  <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon1">-->
            <!--</div>-->
          </form>
        </a>
        <nav class="nav nav-pills flex-column">
           <a class="nav-link" href="#item-1">Name</a>
          <a class="nav-link" href="#item-2">Quick Info</a>
          <a class="nav-link" href="#item-3">Rating</a>
          <a class="nav-link" href="#item-4">About</a>
          <a class="nav-link" href="#item-5">Education and Background</a>
          <a class="nav-link" href="#item-6">Certifications and Skills</a>
        </nav>
      </nav>
    </div>
    <div class="col-8">
      <div class=profile-section left-container-wrapper></div>
      <div data-spy="scroll" data-target="#navbar-article" data-offset="0">
        
        
        
  <!-- Head Card w/ picture and name and location -->
  
      <div class="profile-section">
        <p id="item-1">
        <div class="card mb-3" style="max-width: 100%; border: none;">
          <div class="row no-gutters">
          <div class="col-md-4">
          <img src="https://cdn.pixabay.com/photo/2019/12/06/13/40/anesthesia-4677401_960_720.jpg" class="card-img" style="display: inline-block; width: 270px; height: 270px; border-radius: 50%; object-fit: cover; object-fit: center;">
          </div>
          <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title" style="font-size: x-large;">Evelyn Wong</h5>
            <p class="card-text">Radiology Resident</p>
            <p class="card-text"><small class="text-muted">Stanford, CA</small></p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                </svg> LinkedIn</li>
              <li class="list-group-item">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-video" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 5a2 2 0 0 1 2-2h7.5a2 2 0 0 1 1.983 1.738l3.11-1.382A1 1 0 0 1 16 4.269v7.462a1 1 0 0 1-1.406.913l-3.111-1.382A2 2 0 0 1 9.5 13H2a2 2 0 0 1-2-2V5zm11.5 5.175l3.5 1.556V4.269l-3.5 1.556v4.35zM2 4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h7.5a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H2z"/>
                </svg> Telehealth</li>
              </ul>
          </div>
          </div>
          </div>
        </div>
        </p>
      </div><hr>
      
    <!-- Quick Information -->
    
       
        <div class="profile-section">
        <p id="item-2">
          <div class="row">
            <div class="col-md-6">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
                <path fill-rule="evenodd" d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
              </svg> 95.9
              <p class="small ml-3">Total Research Interest</p>
            </div>
            <div class="col-md-6">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
              </svg> 23
              <p class="small ml-3">Recommendations</p>
            </div>
            </div>
          <div class="row">
              <div class="col-md-6">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bootstrap-reboot" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M1.161 8a6.84 6.84 0 1 0 6.842-6.84.58.58 0 0 1 0-1.16 8 8 0 1 1-6.556 3.412l-.663-.577a.58.58 0 0 1 .227-.997l2.52-.69a.58.58 0 0 1 .728.633l-.332 2.592a.58.58 0 0 1-.956.364l-.643-.56A6.812 6.812 0 0 0 1.16 8zm5.48-.079V5.277h1.57c.881 0 1.416.499 1.416 1.32 0 .84-.504 1.324-1.386 1.324h-1.6zm0 3.75V8.843h1.57l1.498 2.828h1.314L9.377 8.665c.897-.3 1.427-1.106 1.427-2.1 0-1.37-.943-2.246-2.456-2.246H5.5v7.352h1.141z"/>
                </svg> 4,026
                <p class="small ml-3">Reads</p>
              </div>
            <div class="col-md-6">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hourglass-split" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2h-7zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48V8.35zm1 0c0 .701.478 1.236 1.011 1.492A3.5 3.5 0 0 1 11.5 13s-.866-1.299-3-1.48V8.35z"/>
              </svg> Over 100
              <p class="small ml-3">Citations</p>
                
            </div>
          </div>
      </div>
      <hr>
      
   <!-- rating system -->
      <div class="profile-section">
        <h5 id="item-3">Research Ratings</h5>
        <div class="row">
          <div class="col-xs-12 col-md-6 border-right border-md">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-xs-12 col-md-6 text-center">
                        <h1 class="rating-num">
                          18
                        </h1>
                        <div>
                          Research Items
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <div class="row rating-desc">
                            <div class="col-xs-3 col-md-3 text-right">
                              5
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar-striped bg-danger" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    </div>
                                </div>
                            </div>
                            <!-- end 5 -->
                            <div class="col-xs-3 col-md-3 text-right">
                              4
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar-striped bg-danger" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    </div>
                                </div>
                            </div>
                            <!-- end 4 -->
                            <div class="col-xs-3 col-md-3 text-right">
                              3
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar-striped bg-danger" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    </div>
                                </div>
                            </div>
                            <!-- end 3 -->
                            <div class="col-xs-3 col-md-3 text-right">
                                2
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar-striped bg-danger" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    </div>
                                </div>
                            </div>
                            <!-- end 2 -->
                            <div class="col-xs-3 col-md-3 text-right">
                                1
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar-striped bg-danger" role="progressbar" aria-valuenow="80"
                                        aria-valuemin="0" aria-valuemax="100" style="width: 15%">
                                    </div>
                                </div>
                            </div>
                            <!-- end 1 -->
                        </div>
                        <!-- end row -->
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <img src="https://marketingbitz.com/wp-content/uploads/2018/08/BOOST_GUEST_BLOG_IMAGE_SET_5_FIVE_STAR_REVIEW_BG_1200x628px_v1_1.jpg" class="card-img" style="max-width: 50%;" alt="https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg">
        </div>
      </div>
      <hr>
      </div>
      
    <!-- About section -->
   
            <div class="profile-section">
        <h5 id="item-4" style= "text-shadow: .5px .5px 1px #000000;"><b>About</b></h5>
        <p>Interested in pigmentary disorders, photoprotection, procedural dermatology, and connective tissue disease.</p>
      </div>
      
      
    <!-- Education and Background Section -->
    
      <div class="profile-section">
        <h5 id="item-5" style= "text-shadow: .5px .5px 1px #000000;"><b>Education and Background</b></h5>
        <p>
          <h6><b>Specialties</h6></b>
          <ul>
            <li>  
              Doctor of Medicine
            </li>
            <li>
              Radiology
            </li>
          </ul>
          </p>

        <p>
          <h6><b>Education and Training</h6></b>
          <ul>
            <li>
              Stanford University
              <ul>
                <li>
                  August 2015 - May 2020
                </li>
              </ul>
            </li>
            <li>
              Location:
              <ul>
                <li>
                  Stanford, CA, United States
                </li>
              </ul>
            </li>
          </ul>
        </p>
        <p>
          <h6><b>Professional Memberships</h6></b>
          <ul>
            <li>
              Phi Beta Kappa
            </li>
            <li>
              Alpha Omega Alpha Honor Medical Society (AOA)
            </li>
            <li>
              Gold Humanism Honor Society
            </li>
          </ul>
        </p>
        <p>
          <h6><b>Awards and Publications</h6></b>
          <ul>
            <li>
              <a href="#">Reseach Gate Profile</a>
            </li>
            <li>
              National Merit Scholar
            </li>
            <li>
              Anderson Academic/Merit Scholarship
            </li>
            <li>
              Distinguished College Scholar
            </li>
          </ul>
        </p>
      </div>
      
    <!-- Certification and SKills Section -->
    
      <div class="profile-section">
        <h5 id="item-6" style= "text-shadow: .5px .5px 1px #000000;"><b>Certifications and Skills</b></h5>
        <p>
          <h6><b>Certifications</h6></b>
          <ul>
            <li>
              Clinical Research
            </li>
            <li>
              Data Analysis
            </li>
            <li>
              Healthcare Consulting
            </li>
          </ul>
        </p>
        <p>
          <h6><b>Languages Spoken</h6></b>
          <ul>
            <li>
              English
            </li>
            <li>
              Chinese
            </li>
          </ul>
        </p>
      </div>
      
      
      </div>
    </div>
  </div>
</div>

app/views/f_develyns/new.html.erb
<h1>New F Develyn</h1>

<%= render 'form', f_develyn: @f_develyn %>

<%= link_to 'Back', f_develyns_path %>

app/views/f_develyns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_f_develyn_path(@f_develyn) %> |
<%= link_to 'Back', f_develyns_path %>