config/routes.rb
Rails.application.routes.draw do
  resources :f_dzakirs
  resources :f_dpetras
  resources :f_droberts
  resources :f_develyns
  resources :f_dcarries
  resources :f_dowais
  resources :f_djosephs
  resources :f_dalexis
  resources :f_dhalles
  resources :f_dmikaels
  resources :medical_students
  
  devise_for :users
  # Professor told me to move "devise_for :users" after the "resources :users, only: [:show, :edit, :update, :index]". But if I do, the "Too many redirects" error is produced. 
  # Found this on Github: https://github.com/heartcombo/devise/issues/367
  # "RegistrationsController does not allow you to access the new action when you
  # are signed in. If you are signed in and try to access it, it redirects you
  # back to the root_path. Which is going to redirect you again and again.
  
  # My advice is to create another controller which shows you the sign up form,
  # but sends you to the proper registrations controller."
  resources :users, only: [:show, :edit, :update, :index]


  root "users#show" # Changed "users#index" to "users#show" and it sent me to the profile page!
  resources :sign_ins
  resources :join_nows
  
  resources :research_submissions
  resources :blogs do
    resources :comments
  end
  resources :abouts
  resources :specifics
  resources :specialties
  resources :articles
  resources :homes
  

  get 'home/index'
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    validates_presence_of :title
    validates_presence_of :body
    validates_presence_of :author_name
    validates_presence_of :post_type
 #   validates_presence_of :image_url
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/f_dalexi.rb
class FDalexi < ApplicationRecord
end

app/models/f_dcarrie.rb
class FDcarrie < ApplicationRecord
end

app/models/f_develyn.rb
class FDevelyn < ApplicationRecord
end

app/models/f_dhalle.rb
class FDhalle < ApplicationRecord
end

app/models/f_djoseph.rb
class FDjoseph < ApplicationRecord
end

app/models/f_dmikael.rb
class FDmikael < ApplicationRecord
end

app/models/f_dowai.rb
class FDowai < ApplicationRecord
end

app/models/f_dpetra.rb
class FDpetra < ApplicationRecord
end

app/models/f_drobert.rb
class FDrobert < ApplicationRecord
end

app/models/f_dzakir.rb
class FDzakir < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/join_now.rb
class JoinNow < ApplicationRecord
end

app/models/sign_in.rb
class SignIn < ApplicationRecord
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/models/specific.rb
class Specific < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/join_nows_controller.rb
class JoinNowsController < ApplicationController
  before_action :set_join_now, only: [:show, :edit, :update, :destroy]

  # GET /join_nows
  # GET /join_nows.json
  def index
    @join_nows = JoinNow.all
  end

  # GET /join_nows/1
  # GET /join_nows/1.json
  def show
  end

  # GET /join_nows/new
  def new
    @join_now = JoinNow.new
  end

  # GET /join_nows/1/edit
  def edit
  end

  # POST /join_nows
  # POST /join_nows.json
  def create
    @join_now = JoinNow.new(join_now_params)

    respond_to do |format|
      if @join_now.save
        format.html { redirect_to @join_now, notice: 'Join now was successfully created.' }
        format.json { render :show, status: :created, location: @join_now }
      else
        format.html { render :new }
        format.json { render json: @join_now.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /join_nows/1
  # PATCH/PUT /join_nows/1.json
  def update
    respond_to do |format|
      if @join_now.update(join_now_params)
        format.html { redirect_to @join_now, notice: 'Join now was successfully updated.' }
        format.json { render :show, status: :ok, location: @join_now }
      else
        format.html { render :edit }
        format.json { render json: @join_now.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /join_nows/1
  # DELETE /join_nows/1.json
  def destroy
    @join_now.destroy
    respond_to do |format|
      format.html { redirect_to join_nows_url, notice: 'Join now was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join_now
      @join_now = JoinNow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def join_now_params
      params.require(:join_now).permit(:title, :string, :data_text, :text)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/join_nows_helper.rb
module JoinNowsHelper
end

app/views/join_nows/_form.html.erb
<%= form_for(join_now) do |f| %>
  <% if join_now.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(join_now.errors.count, "error") %> prohibited this join_now from being saved:</h2>

      <ul>
      <% join_now.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :data_text %>
    <%= f.text_field :data_text %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/join_nows/edit.html.erb
<h1>Editing Join Now</h1>

<%= render 'form', join_now: @join_now %>

<%= link_to 'Show', @join_now %> |
<%= link_to 'Back', join_nows_path %>

app/views/join_nows/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<!--<h1>Join Nows</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>String</th>-->
<!--      <th>Data text</th>-->
<!--      <th>Text</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @join_nows.each do |join_now| %>-->
<!--      <tr>-->
<!--        <td><%= join_now.title %></td>-->
<!--        <td><%= join_now.string %></td>-->
<!--        <td><%= join_now.data_text %></td>-->
<!--        <td><%= join_now.text %></td>-->
<!--        <td><%= link_to 'Show', join_now %></td>-->
<!--        <td><%= link_to 'Edit', edit_join_now_path(join_now) %></td>-->
<!--        <td><%= link_to 'Destroy', join_now, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Join Now', new_join_now_path %>-->

<form action="action_page.php" style="border:1px solid #ccc">
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>

    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

    <div class="clearfix">
      <button type="button" class="cancelbtn">Cancel</button>
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>

app/views/join_nows/new.html.erb
<h1>New Join Now</h1>

<%= render 'form', join_now: @join_now %>

<%= link_to 'Back', join_nows_path %>

app/views/join_nows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @join_now.title %>
</p>

<p>
  <strong>String:</strong>
  <%= @join_now.string %>
</p>

<p>
  <strong>Data text:</strong>
  <%= @join_now.data_text %>
</p>

<p>
  <strong>Text:</strong>
  <%= @join_now.text %>
</p>

<%= link_to 'Edit', edit_join_now_path(@join_now) %> |
<%= link_to 'Back', join_nows_path %>