config/routes.rb
Rails.application.routes.draw do
  resources :f_dzakirs
  resources :f_dpetras
  resources :f_droberts
  resources :f_develyns
  resources :f_dcarries
  resources :f_dowais
  resources :f_djosephs
  resources :f_dalexis
  resources :f_dhalles
  resources :f_dmikaels
  resources :medical_students
  
  devise_for :users
  # Professor told me to move "devise_for :users" after the "resources :users, only: [:show, :edit, :update, :index]". But if I do, the "Too many redirects" error is produced. 
  # Found this on Github: https://github.com/heartcombo/devise/issues/367
  # "RegistrationsController does not allow you to access the new action when you
  # are signed in. If you are signed in and try to access it, it redirects you
  # back to the root_path. Which is going to redirect you again and again.
  
  # My advice is to create another controller which shows you the sign up form,
  # but sends you to the proper registrations controller."
  resources :users, only: [:show, :edit, :update, :index]


  root "users#show" # Changed "users#index" to "users#show" and it sent me to the profile page!
  resources :sign_ins
  resources :join_nows
  
  resources :research_submissions
  resources :blogs do
    resources :comments
  end
  resources :abouts
  resources :specifics
  resources :specialties
  resources :articles
  resources :homes
  

  get 'home/index'
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    validates_presence_of :title
    validates_presence_of :body
    validates_presence_of :author_name
    validates_presence_of :post_type
 #   validates_presence_of :image_url
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/f_dalexi.rb
class FDalexi < ApplicationRecord
end

app/models/f_dcarrie.rb
class FDcarrie < ApplicationRecord
end

app/models/f_develyn.rb
class FDevelyn < ApplicationRecord
end

app/models/f_dhalle.rb
class FDhalle < ApplicationRecord
end

app/models/f_djoseph.rb
class FDjoseph < ApplicationRecord
end

app/models/f_dmikael.rb
class FDmikael < ApplicationRecord
end

app/models/f_dowai.rb
class FDowai < ApplicationRecord
end

app/models/f_dpetra.rb
class FDpetra < ApplicationRecord
end

app/models/f_drobert.rb
class FDrobert < ApplicationRecord
end

app/models/f_dzakir.rb
class FDzakir < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/join_now.rb
class JoinNow < ApplicationRecord
end

app/models/research_submission.rb
class ResearchSubmission < ApplicationRecord
end

app/models/sign_in.rb
class SignIn < ApplicationRecord
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/models/specific.rb
class Specific < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/research_submissions_controller.rb
class ResearchSubmissionsController < ApplicationController
  before_action :set_research_submission, only: [:show, :edit, :update, :destroy]

  # GET /research_submissions
  # GET /research_submissions.json
  def index
    @research_submissions = ResearchSubmission.all
  end

  # GET /research_submissions/1
  # GET /research_submissions/1.json
  def show
  end

  # GET /research_submissions/new
  def new
    @research_submission = ResearchSubmission.new
  end

  # GET /research_submissions/1/edit
  def edit
  end

  # POST /research_submissions
  # POST /research_submissions.json
  def create
    @research_submission = ResearchSubmission.new(research_submission_params)

    respond_to do |format|
      if @research_submission.save
        format.html { redirect_to @research_submission, notice: 'Research submission was successfully created.' }
        format.json { render :show, status: :created, location: @research_submission }
      else
        format.html { render :new }
        format.json { render json: @research_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_submissions/1
  # PATCH/PUT /research_submissions/1.json
  def update
    respond_to do |format|
      if @research_submission.update(research_submission_params)
        format.html { redirect_to @research_submission, notice: 'Research submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @research_submission }
      else
        format.html { render :edit }
        format.json { render json: @research_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_submissions/1
  # DELETE /research_submissions/1.json
  def destroy
    @research_submission.destroy
    respond_to do |format|
      format.html { redirect_to research_submissions_url, notice: 'Research submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_submission
      @research_submission = ResearchSubmission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def research_submission_params
      params.require(:research_submission).permit(:page_title, :string, :submission_title, :string, :body_of_submission, :text, :comments, :text, :authorID, :string, :author_name, :string)
    end
end

app/helpers/research_submissions_helper.rb
module ResearchSubmissionsHelper
end

app/views/research_submissions/_form.html.erb
<%= form_for(research_submission) do |f| %>
  <% if research_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(research_submission.errors.count, "error") %> prohibited this research_submission from being saved:</h2>

      <ul>
      <% research_submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_title %>
    <%= f.text_field :page_title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :submission_title %>
    <%= f.text_field :submission_title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :body_of_submission %>
    <%= f.text_field :body_of_submission %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_field :comments %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :authorID %>
    <%= f.text_field :authorID %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_submissions/edit.html.erb
<h1>Editing Research Submission</h1>

<%= render 'form', research_submission: @research_submission %>

<%= link_to 'Show', @research_submission %> |
<%= link_to 'Back', research_submissions_path %>

app/views/research_submissions/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="card text-black" style="max-width: 55rem; max-height: 50rem;" align= "middle">
    <h1 class="card-title" style= "font-size: 40px;">Publishing with the University of Houston Student Medical Review</h1>
    <p class="card-text">Leading scientific inquiry</p>
  </div>
  <img class="card-img-bottom" src="https://cdn.pixabay.com/photo/2018/09/27/14/14/analysis-3707159_1280.jpg" alt="Card image cap"style= "max-width: 55rem; max-height: 30rem; object-fit: cover;">
</div>

<p></p><%= link_to 'New Research Submission', new_research_submission_path %>

<form>
    <form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <p></p><label for="validationCustom01">First name</label>
      <input type="text" class="form-control" id="validationCustom01" placeholder="First name" value="" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <p></p><label for="validationCustom02">Last name</label>
      <input type="text" class="form-control" id="validationCustom02" placeholder="Last name" value="" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <p></p><label for="validationCustom02">Email Address</label>
      <input type="text" class="form-control" id="validationCustom02" placeholder="e.g., janedoe@email.com" value="" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="validationCustom03">City</label>
      <input type="text" class="form-control" id="validationCustom03" placeholder="City" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
        <div class="form-row col-md-4 mb-3">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationCustom05">Zip</label>
      <input type="text" class="form-control" id="validationCustom05" placeholder="Zip" required>
      <div class="invalid-feedback">
        Please provide a valid zip.
      </div>
    </div>
  </div>
</form>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

</script>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Is this a competition entry?</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
          <label class="form-check-label" for="gridRadios1">
            Yes
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
          <label class="form-check-label" for="gridRadios2">
            No
          </label>
        </div>
      </div>
    </div>
  </fieldset>
  
  <form>
  <div class="form-group">
    <label for="formGroupExampleInput">Title</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Title of your article, poster, etc.">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput2">Authors</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Names of your authors separated by commas (e.g., 'A.Loya, S.Patel, et. al.')">
  </div>
  <div class="form-group">
    <label for="formGroupExampleInput3">Summary</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Input abstract here. 300 word limit">
  </div>  
</form>

    <div class="form-group">
    <label for="exampleFormControlFile1">Upload File</label>
    <input type="file" class="form-control-file" id="exampleFormControlFile1">
    </div>
      <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        I accept the Terms and Conditions of submitting to the University of Houston Medical Journal
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
    <button class="btn btn-primary" type="submit" align="middle"> Submit</button>

</form>

app/views/research_submissions/new.html.erb
<h1>New Research Submission</h1>

<%= render 'form', research_submission: @research_submission %>

<%= link_to 'Back', research_submissions_path %>

app/views/research_submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page title:</strong>
  <%= @research_submission.page_title %>
</p>

<p>
  <strong>String:</strong>
  <%= @research_submission.string %>
</p>

<p>
  <strong>Submission title:</strong>
  <%= @research_submission.submission_title %>
</p>

<p>
  <strong>String:</strong>
  <%= @research_submission.string %>
</p>

<p>
  <strong>Body of submission:</strong>
  <%= @research_submission.body_of_submission %>
</p>

<p>
  <strong>Text:</strong>
  <%= @research_submission.text %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @research_submission.comments %>
</p>

<p>
  <strong>Text:</strong>
  <%= @research_submission.text %>
</p>

<p>
  <strong>Authorid:</strong>
  <%= @research_submission.authorID %>
</p>

<p>
  <strong>String:</strong>
  <%= @research_submission.string %>
</p>

<p>
  <strong>Author name:</strong>
  <%= @research_submission.author_name %>
</p>

<p>
  <strong>String:</strong>
  <%= @research_submission.string %>
</p>

<%= link_to 'Edit', edit_research_submission_path(@research_submission) %> |
<%= link_to 'Back', research_submissions_path %>