config/routes.rb
Rails.application.routes.draw do
  resources :f_dzakirs
  resources :f_dpetras
  resources :f_droberts
  resources :f_develyns
  resources :f_dcarries
  resources :f_dowais
  resources :f_djosephs
  resources :f_dalexis
  resources :f_dhalles
  resources :f_dmikaels
  resources :medical_students
  
  devise_for :users
  # Professor told me to move "devise_for :users" after the "resources :users, only: [:show, :edit, :update, :index]". But if I do, the "Too many redirects" error is produced. 
  # Found this on Github: https://github.com/heartcombo/devise/issues/367
  # "RegistrationsController does not allow you to access the new action when you
  # are signed in. If you are signed in and try to access it, it redirects you
  # back to the root_path. Which is going to redirect you again and again.
  
  # My advice is to create another controller which shows you the sign up form,
  # but sends you to the proper registrations controller."
  resources :users, only: [:show, :edit, :update, :index]


  root "users#show" # Changed "users#index" to "users#show" and it sent me to the profile page!
  resources :sign_ins
  resources :join_nows
  
  resources :research_submissions
  resources :blogs do
    resources :comments
  end
  resources :abouts
  resources :specifics
  resources :specialties
  resources :articles
  resources :homes
  

  get 'home/index'
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    validates_presence_of :title
    validates_presence_of :body
    validates_presence_of :author_name
    validates_presence_of :post_type
 #   validates_presence_of :image_url
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
end

app/models/f_dalexi.rb
class FDalexi < ApplicationRecord
end

app/models/f_dcarrie.rb
class FDcarrie < ApplicationRecord
end

app/models/f_develyn.rb
class FDevelyn < ApplicationRecord
end

app/models/f_dhalle.rb
class FDhalle < ApplicationRecord
end

app/models/f_djoseph.rb
class FDjoseph < ApplicationRecord
end

app/models/f_dmikael.rb
class FDmikael < ApplicationRecord
end

app/models/f_dowai.rb
class FDowai < ApplicationRecord
end

app/models/f_dpetra.rb
class FDpetra < ApplicationRecord
end

app/models/f_drobert.rb
class FDrobert < ApplicationRecord
end

app/models/f_dzakir.rb
class FDzakir < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/join_now.rb
class JoinNow < ApplicationRecord
end

app/models/sign_in.rb
class SignIn < ApplicationRecord
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/models/specific.rb
class Specific < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/specifics_controller.rb
class SpecificsController < ApplicationController
  before_action :set_specific, only: [:show, :edit, :update, :destroy]

  # GET /specifics
  # GET /specifics.json
  def index
    @specifics = Specific.all
  end

  # GET /specifics/1
  # GET /specifics/1.json
  def show
  end

  # GET /specifics/new
  def new
    @specific = Specific.new
  end

  # GET /specifics/1/edit
  def edit
  end

  # POST /specifics
  # POST /specifics.json
  def create
    @specific = Specific.new(specific_params)

    respond_to do |format|
      if @specific.save
        format.html { redirect_to @specific, notice: 'Specific was successfully created.' }
        format.json { render :show, status: :created, location: @specific }
      else
        format.html { render :new }
        format.json { render json: @specific.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specifics/1
  # PATCH/PUT /specifics/1.json
  def update
    respond_to do |format|
      if @specific.update(specific_params)
        format.html { redirect_to @specific, notice: 'Specific was successfully updated.' }
        format.json { render :show, status: :ok, location: @specific }
      else
        format.html { render :edit }
        format.json { render json: @specific.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specifics/1
  # DELETE /specifics/1.json
  def destroy
    @specific.destroy
    respond_to do |format|
      format.html { redirect_to specifics_url, notice: 'Specific was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specific
      @specific = Specific.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specific_params
      params.require(:specific).permit(:Specialty, :category_name, :string, :description, :text, :data_type, :string, :data_title, :string, :description, :authors, :string, :authorID, :string)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/specifics_helper.rb
module SpecificsHelper
end

app/views/specifics/_form.html.erb
<%= form_for(specific) do |f| %>
  <% if specific.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specific.errors.count, "error") %> prohibited this specific from being saved:</h2>

      <ul>
      <% specific.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Specialty %>
    <%= f.text_field :Specialty %>
  </div>

  <div class="field">
    <%= f.label :category_name %>
    <%= f.text_field :category_name %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :data_type %>
    <%= f.text_field :data_type %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :data_title %>
    <%= f.text_field :data_title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :authors %>
    <%= f.text_field :authors %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :authorID %>
    <%= f.text_field :authorID %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specifics/edit.html.erb
<h1>Editing Specific</h1>

<%= render 'form', specific: @specific %>

<%= link_to 'Show', @specific %> |
<%= link_to 'Back', specifics_path %>

app/views/specifics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specifics</h1>

<table>
  <thead>
    <tr>
      <th>Specialty</th>
      <th>Category name</th>
      <th>String</th>
      <th>Description</th>
      <th>Text</th>
      <th>Data type</th>
      <th>String</th>
      <th>Data title</th>
      <th>String</th>
      <th>Description</th>
      <th>Authors</th>
      <th>String</th>
      <th>Authorid</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specifics.each do |specific| %>
      <tr>
        <td><%= specific.Specialty %></td>
        <td><%= specific.category_name %></td>
        <td><%= specific.string %></td>
        <td><%= specific.description %></td>
        <td><%= specific.text %></td>
        <td><%= specific.data_type %></td>
        <td><%= specific.string %></td>
        <td><%= specific.data_title %></td>
        <td><%= specific.string %></td>
        <td><%= specific.description %></td>
        <td><%= specific.authors %></td>
        <td><%= specific.string %></td>
        <td><%= specific.authorID %></td>
        <td><%= specific.string %></td>
        <td><%= link_to 'Show', specific %></td>
        <td><%= link_to 'Edit', edit_specific_path(specific) %></td>
        <td><%= link_to 'Destroy', specific, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specific', new_specific_path %>

app/views/specifics/new.html.erb
<h1>New Specific</h1>

<%= render 'form', specific: @specific %>

<%= link_to 'Back', specifics_path %>

app/views/specifics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialty:</strong>
  <%= @specific.Specialty %>
</p>

<p>
  <strong>Category name:</strong>
  <%= @specific.category_name %>
</p>

<p>
  <strong>String:</strong>
  <%= @specific.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @specific.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @specific.text %>
</p>

<p>
  <strong>Data type:</strong>
  <%= @specific.data_type %>
</p>

<p>
  <strong>String:</strong>
  <%= @specific.string %>
</p>

<p>
  <strong>Data title:</strong>
  <%= @specific.data_title %>
</p>

<p>
  <strong>String:</strong>
  <%= @specific.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @specific.description %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @specific.authors %>
</p>

<p>
  <strong>String:</strong>
  <%= @specific.string %>
</p>

<p>
  <strong>Authorid:</strong>
  <%= @specific.authorID %>
</p>

<p>
  <strong>String:</strong>
  <%= @specific.string %>
</p>

<%= link_to 'Edit', edit_specific_path(@specific) %> |
<%= link_to 'Back', specifics_path %>